training_pipeline_config:
  pipeline_name: visa 
  artifact_dir : artifact 

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ISHAWANT/Data_set/main/Visadataset.csv 
  raw_data_dir : raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

#DATA VALIDATION 
data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml 
  report_file_name: report.json
  schema_page_file_name: report.html 

#DATA TRANSFORMATION 
data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test 
  preprocessing_dir: preprocessed 
  preprocessed_object_file_name: preprocessed.pkl 
